#!/usr/bin/env python3
# ============================================
# INFINITE SQUADS — ROSTER GENERATOR
# Single source of truth. Each card is authored ONCE here and
# emitted into a synchronized megaRoster.ts, which feeds
# presetCards + cardRegistry + avatar with zero desync risk.
# Add batches to BATCHES, rerun: python3 scripts/gen_roster.py
# ============================================
import json, sys, os, hashlib

# c(name, nick, era, tags, core[mi,br,ch,cx,gr,cl], stats[[label,val,emoji]x6], rarity, av{...})
def c(name, nick, era, tags, core, stats, rarity, av):
    assert len(core) == 6, name
    assert len(stats) == 6, name
    for label, val, emoji in stats:
        assert 0 <= val <= 100, (name, label, val)
    for k in core:
        assert 1 <= k <= 99, (name, k)
    return dict(name=name, nick=nick, era=era, tags=tags, core=core, stats=stats, rarity=rarity, av=av)

HAIR={"bald","wild","afro","slick","bowl","bun","furhat","tophat","bicorne","bowler","wig","helmet","bandana","spiky","buzzcut","dreads","bow","headscarf","laurel","mohawk","wavy","ponytail","blob"}
FACIAL={"none","mustache","full","goatee","horseshoe","longbeard","stubble","sideburns"}
EYES={"normal","shades","wink","angry","wide","sleepy","smug","intense","dot"}
MOUTH={"smile","grin","smirk","frown","neutral","open","smug"}
def av(bg, skin, hair, hairColor, facial, eyes, mouth, prop):
    assert hair in HAIR, "bad hair: "+hair
    assert facial in FACIAL, "bad facial: "+facial
    assert eyes in EYES, "bad eyes: "+eyes
    assert mouth in MOUTH, "bad mouth: "+mouth
    return dict(bg=bg, skin=skin, hair=hair, hairColor=hairColor, facial=facial, eyes=eyes, mouth=mouth, prop=prop)

# Compact constructor for high-volume themed batches. Names and jokes stay hand-authored;
# core stats, six on-theme flavor stats, and doodle traits are deterministically derived.
# This keeps expansion authoring readable without weakening the generator's validation.
THEMES = {
 "monster":[("Lair Security","🏚️"),("Villager Relations","🔥"),("Boss Fight Energy","⚔️"),("Subtlety","🥷"),("Legend Longevity","📜"),("Merch Potential","🧸")],
 "job":[("On-The-Clock Power","⏱️"),("Email Response Time","📧"),("Customer Patience","😮‍💨"),("Break Room Lore","☕"),("Certification Confidence","📋"),("Work Chat Presence","💬")],
 "object":[("Daily Annoyance","😤"),("Shelf Life","📦"),("Cleanup Difficulty","🧹"),("Unexpected Violence","💥"),("Household Ubiquity","🏠"),("Sentimental Value","💖")],
 "animal":[("Snack Detection","🍖"),("Good Behavior","😇"),("Escape Skill","🚪"),("Chaos Per Pound","🌪️"),("Nap Efficiency","💤"),("Internet Appeal","📱")],
 "storybook":[("Plot Armor","📖"),("Decision Quality","🤔"),("Monologue Length","🎭"),("Costume Budget","👑"),("Adaptation Count","🎬"),("Public Domain Power","🏛️")],
 "online":[("Screen Time","📱"),("Reply Speed","⚡"),("Offline Skills","🌲"),("Algorithm Favor","📈"),("Group Chat Damage","💬"),("Main Character Energy","✨")],
}
TAG_BOOSTS = {
 "warlord":(24,8,0,12,12,8), "ruler":(6,12,12,2,8,20), "genius":(-8,30,0,-2,2,10),
 "inventor":(-2,22,0,8,4,8), "philosopher":(-8,24,6,-4,10,6), "artist":(-6,12,16,10,0,12),
 "musician":(-4,4,18,12,2,18), "athlete":(24,2,4,2,20,12), "entertainer":(0,2,24,12,2,18),
 "hustler":(2,12,12,10,12,14), "villain":(12,4,-12,18,10,8), "wholesome":(-4,4,24,-10,10,10),
 "chaos":(4,-8,2,32,6,10), "survivor":(10,6,0,4,28,6), "animal":(16,-8,10,12,18,8),
 "entity":(8,6,-4,16,18,10), "cryptid":(18,2,-2,20,22,16), "gamer":(-4,16,-6,12,8,10),
 "internet":(-6,6,4,18,2,18),
}
PALETTES=[("#263859","#d9a878","wild","#2a1a0a"),("#5a2a5a","#e6c39a","wavy","#3a2a1a"),("#285943","#c98f5e","buzzcut","#1a1a1a"),("#7a3a2a","#e0b28a","bowl","#5a3a1a"),("#2f4858","#a8703a","slick","#1a1a1a"),("#6b5b2a","#f0d8c0","bun","#c9622a")]
def q(name, nick, era, tags, rarity, prop, theme):
    raw = hashlib.sha256(name.encode()).digest()
    core = [45 + (raw[i] % 15) for i in range(6)]
    for tag in tags:
        core = [v + d for v,d in zip(core, TAG_BOOSTS[tag])]
    core = [max(1, min(99, v)) for v in core]
    bases = [88, 28, 76, 61, 84, 72]
    stats = [[label, max(0,min(100, base + (raw[i+6] % 21) - 10)), emoji]
             for i,((label,emoji),base) in enumerate(zip(THEMES[theme],bases))]
    bg,skin,hair,hairColor = PALETTES[raw[12] % len(PALETTES)]
    if "animal" in tags or "entity" in tags or "cryptid" in tags: hair = "blob"
    facial = ["none","stubble","goatee","full"][raw[13] % 4] if hair != "blob" else "none"
    eyes = ["normal","wink","smug","intense","wide"][raw[14] % 5]
    mouth = ["smile","grin","smirk","neutral","frown"][raw[15] % 5]
    return c(name,nick,era,tags,core,stats,rarity,av(bg,skin,hair,hairColor,facial,eyes,mouth,prop))

# ─────────────────────────────────────────────
# BATCH 1 — GREEK / ROMAN / NORSE / EGYPTIAN MYTH + WORLD FOLKLORE
# All public domain. All universally recognized. Nobody owns Zeus.
# ─────────────────────────────────────────────
BATCH_1 = [
 c("Poseidon","Landlord Of The Sea","ancient",["ruler","entity"],[90,58,52,82,84,88],
   [["Trident Handling",96,"🔱"],["Anger Management",22,"🌊"],["Coastal Property Damage",95,"🏚️"],
    ["Landlocked Vacations",8,"🏜️"],["Grudge Duration",99,"⏳"],["Horse Invention Credit",70,"🐴"]],
   "legendary", av("#12496b","#cdb89a","wavy","#c9d6e0","longbeard","intense","neutral","🔱")),
 c("Hades","Underworld HR Director","ancient",["ruler","villain"],[80,80,48,52,92,78],
   [["Real Estate Portfolio",90,"🏰"],["PR Department",12,"💀"],["Guard Dog Loyalty",99,"🐕"],
    ["Sunlight Tolerance",9,"🌑"],["Dating Success Rate",30,"🌸"],["Job Security",99,"🔥"]],
   "legendary", av("#2a1030","#c9a884","slick","#1a1a1a","goatee","intense","neutral","🔥")),
 c("Zeus Prime","Cannot Keep It In The Toga","ancient",["ruler","warlord","chaos"],[92,70,80,78,80,97],
   [["Lightning Aim",97,"⚡"],["Marital Fidelity",4,"💍"],["Shapeshifting (Suspicious)",90,"🦢"],
    ["Anger Issues",88,"🌩️"],["Divine Authority",96,"👑"],["Restraint",6,"🍑"]],
   "holo", av("#1a3a6a","#e6c39a","laurel","#e8e8e8","longbeard","intense","smug","⚡")),
 c("Athena","Carried Olympus Academically","ancient",["genius","warlord"],[72,98,66,20,82,86],
   [["Strategy",98,"🦉"],["Losing Arguments",5,"📚"],["Owl Maintenance",90,"🦉"],
    ["Ability To Relax",30,"🧘"],["Born-From-A-Head Trauma",60,"🧠"],["Wisdom",99,"✨"]],
   "holo", av("#4a5a2a","#e0bd93","helmet","#b0a060","none","intense","neutral","🦉")),
 c("Ares","All Gym, No Plan","ancient",["warlord","chaos"],[95,28,46,90,82,60],
   [["Bloodlust",99,"⚔️"],["Tactical Planning",18,"🗺️"],["Impulse Control",8,"💢"],
    ["Getting Stabbed",72,"🩸"],["Gym Gains",93,"💪"],["Popularity Among Gods",10,"👎"]],
   "gold", av("#7a1a1a","#d9a06a","helmet","#8a1a1a","stubble","angry","frown","⚔️")),
 c("Aphrodite","Started Wars By Accident","ancient",["ruler","entertainer"],[40,62,99,58,52,95],
   [["Rizz",99,"💘"],["Humility",10,"💅"],["Drama Generation",95,"🎭"],
    ["Loyalty",25,"💔"],["Beauty Sleep",90,"😴"],["Accidental War Starting",88,"🏹"]],
   "holo", av("#c94f8a","#e6c39a","wavy","#d9b84a","none","wink","smirk","💘")),
 c("Apollo","Insufferably Multitalented","ancient",["musician","entertainer"],[66,82,88,42,60,92],
   [["Lyre Solos",95,"🎵"],["Modesty",15,"☀️"],["Sun Punctuality",85,"🌅"],
    ["Handling Rejection",20,"🌿"],["Prophecy Accuracy",80,"🔮"],["Twin Rivalry",55,"🏹"]],
   "legendary", av("#e8a33a","#e6c39a","wavy","#d9b84a","none","smug","smirk","🎵")),
 c("Artemis","Zero Tolerance Policy","ancient",["athlete","survivor"],[80,72,50,45,90,74],
   [["Archery",97,"🏹"],["Small Talk",15,"🌲"],["Wildlife Bond",92,"🦌"],
    ["Patience For Men",5,"🚫"],["Night Shifts",88,"🌙"],["Grudge Enforcement",99,"🦌"]],
   "gold", av("#2a4a3a","#dbb890","ponytail","#3a2a1a","none","intense","neutral","🏹")),
 c("Hermes","Same-Day Delivery","ancient",["hustler","entertainer"],[60,86,80,76,72,82],
   [["Delivery Speed",99,"👟"],["Honesty",25,"📦"],["Sneaking",95,"🤫"],
    ["Ability To Sit Still",8,"💨"],["Multitasking",90,"📱"],["Baby-Age Cattle Theft",88,"🐄"]],
   "gold", av("#c9a227","#e0bd93","helmet","#d4af37","none","wink","grin","👟")),
 c("Dionysus","Never Had A Sober Thought","ancient",["entertainer","chaos"],[52,56,88,95,62,86],
   [["Party Starting",99,"🍷"],["Sobriety",5,"🍇"],["Vibe Curation",92,"🎉"],
    ["Impulse Control",12,"🍷"],["Hangover Immunity",80,"😵"],["Literal Cult Following",90,"🐆"]],
   "legendary", av("#5a1a3a","#d9a878","wavy","#3a1a0a","stubble","sleepy","grin","🍷")),
 c("Hephaestus","Outkicked His Coverage","ancient",["inventor","genius"],[72,95,40,32,90,60],
   [["Forging",98,"🔨"],["Marriage Out Of League",25,"💍"],["Craftsmanship",96,"⚙️"],
    ["Getting Thrown Off Olympus",70,"🌋"],["Work Ethic",92,"🛠️"],["Petty Revenge Traps",85,"🕸️"]],
   "gold", av("#4a2a1a","#c98f5e","wild","#2a1a0a","full","angry","neutral","🔨")),
 c("Hera","Marriage Enforcement Division","ancient",["ruler","villain"],[60,82,70,60,86,88],
   [["Marriage Enforcement",95,"👑"],["Trust In Husband",5,"👁️"],["Revenge Plots",97,"🦚"],
    ["Forgiveness",8,"❄️"],["Peacock PR",80,"🦚"],["Surveillance Coverage",99,"📡"]],
   "legendary", av("#5a1a5a","#e6c39a","bun","#2a1a0a","none","smug","frown","👑")),
 c("Cronus","Ate The Kids To Keep The Job","ancient",["warlord","villain"],[88,60,30,72,86,70],
   [["Eating Own Children",99,"😬"],["Parenting",3,"👶"],["Time Management",85,"⏳"],
    ["Paranoia",95,"👁️"],["Throne Retention",30,"🪑"],["Sickle Technique",82,"🌾"]],
   "gold", av("#3a2a1a","#c9a884","wild","#8a8a8a","longbeard","intense","frown","⏳")),
 c("Prometheus","Committed The Original Piracy","ancient",["genius","survivor"],[55,92,60,66,99,76],
   [["Fire Piracy",99,"🔥"],["Cover Story",10,"🦅"],["Human PR Campaign",90,"🗿"],
    ["Liver Regeneration",99,"🩸"],["Pain Tolerance",99,"⛓️"],["HR Complaint Filing",5,"📝"]],
   "holo", av("#6a3a1a","#d9a878","wild","#3a2a1a","full","intense","neutral","🔥")),
 c("Atlas","Held The Whole Thing Up","ancient",["survivor"],[97,42,46,30,99,70],
   [["Planetary Deadlift",99,"🌍"],["Break Time",2,"⏸️"],["Posture",60,"🧍"],
    ["Vacation Days Used",0,"🏖️"],["Endurance",99,"💪"],["Complaining About It",95,"😤"]],
   "gold", av("#3a3a4a","#c98f5e","wild","#2a1a0a","full","intense","frown","🌍")),
 c("Cupid","Fires Without Consent Forms","ancient",["entity","entertainer"],[30,55,90,72,55,80],
   [["Arrow Aim",92,"💘"],["Consent Paperwork",15,"📋"],["Match Accuracy",60,"❤️"],
    ["Chaos Per Arrow",90,"🏹"],["Diaper Aerodynamics",70,"👼"],["Retirement Plan",0,"♾️"]],
   "silver", av("#f5b8c8","#f0d8c0","bowl","#d9b84a","none","wink","grin","💘")),
 c("Midas","Ruined Dinner Forever","classical",["ruler","hustler"],[45,50,70,60,55,88],
   [["Net Worth",99,"🪙"],["Foresight",8,"✨"],["Touch Control",5,"🖐️"],
    ["Snack Options",3,"🍗"],["Personal Branding",90,"👑"],["Daughter Retention",10,"🗿"]],
   "gold", av("#c9a227","#d4af37","laurel","#d4af37","goatee","wide","open","🪙")),
 c("Pandora","Should Not Have Opened It","ancient",["chaos","survivor"],[30,55,80,88,52,70],
   [["Curiosity",99,"📦"],["Impulse Control",4,"🔓"],["Blame Deflection",60,"🤷"],
    ["Box Security",2,"📭"],["Hope Retention",40,"🕊️"],["Consequence Generation",95,"💀"]],
   "silver", av("#8a6a2a","#e6c39a","wavy","#5a3a1a","none","wide","open","📦")),
 c("The Sphinx","Riddle-Gatekeeping Menace","ancient",["villain","genius"],[75,90,55,60,80,74],
   [["Riddle Difficulty",95,"🦁"],["Chill",20,"🏜️"],["Gatekeeping",92,"🚧"],
    ["Losing Gracefully",5,"😾"],["Desert Cardio",70,"🐾"],["Ego",88,"👑"]],
   "gold", av("#c9a86a","#c98f5e","headscarf","#c9a227","none","smug","smirk","🦁")),
 c("Achilles","One Bad Ankle From Greatness","classical",["athlete","warlord"],[96,60,66,50,70,90],
   [["Melee Combat",99,"🛡️"],["Ankle Care",3,"🦶"],["Ego",92,"💢"],
    ["Anger Management",15,"🔥"],["Epic Poem PR",95,"📜"],["Life Insurance",10,"🏹"]],
   "legendary", av("#8a1a1a","#d9a06a","helmet","#8a8a8a","stubble","intense","neutral","🛡️")),
 c("Odysseus","Took The Scenic Route (10 Years)","classical",["genius","survivor"],[70,96,75,70,88,82],
   [["Scheming",97,"🐴"],["Commute Time",2,"⛵"],["Lying On The Spot",95,"🗣️"],
    ["Crew Retention",5,"💀"],["Marital Patience",90,"🏹"],["1-Star Cyclops Review",99,"👁️"]],
   "holo", av("#2a5a7a","#d9a878","bowl","#3a2a1a","stubble","smug","smirk","🐴")),
 c("Cerberus","Three Heads, One Job","ancient",["animal","villain"],[88,40,38,55,90,72],
   [["Guard Duty",99,"🐕"],["Treats Required (x3)",90,"🦴"],["Chill",15,"😤"],
    ["Fetch",60,"🎾"],["Escapees Allowed",2,"🚪"],["Vet Bill Multiplier",99,"💉"]],
   "gold", av("#2a1a2a","#4a3a2a","blob","#000","none","angry","open","🐕")),
 c("Thor","Solves Problems By Hitting Them","classical",["warlord","athlete"],[96,55,76,60,88,92],
   [["Hammer Swings",98,"🔨"],["Worthiness",90,"⚡"],["Drinking Contests",85,"🍺"],
    ["Helmet Retention",40,"🪖"],["Thunder Punctuality",80,"🌩️"],["Snake Beef",70,"🐍"]],
   "legendary", av("#3a5a7a","#e0bd93","wild","#d9b84a","full","intense","grin","🔨")),
 c("Odin","Traded An Eye For Wifi","classical",["ruler","genius"],[82,96,60,55,90,90],
   [["Wisdom",98,"👁️"],["Eye Retention",50,"🩹"],["Raven Intelligence Network",92,"🐦‍⬛"],
    ["Peace Preference",30,"⚔️"],["Prophecy",88,"🔮"],["Self-Sacrifice To Self",99,"🌳"]],
   "holo", av("#3a3a4a","#d9c0a8","furhat","#c9c9c9","longbeard","smug","neutral","👁️")),
 c("Loki","Trust Issues Personified","classical",["hustler","villain","chaos"],[55,92,80,97,76,82],
   [["Trickery",99,"🐍"],["Trustworthiness",4,"🎭"],["Shapeshifting",95,"🦎"],
    ["Loyalty",15,"🔪"],["Escaping The Blame",85,"💨"],["Gave Birth To A Horse",100,"🐴"]],
   "legendary", av("#2a5a3a","#e0bd93","slick","#3a1a0a","none","smug","smirk","🐍")),
 c("Fenrir","They Should Not Have Chained Him","classical",["villain","animal"],[93,50,30,70,90,66],
   [["Bite Force",99,"🐺"],["Being Chained",20,"⛓️"],["Growth Rate",95,"📈"],
    ["Trust In Gods",3,"😠"],["Apocalypse Readiness",92,"🌒"],["Good Boy Points",30,"🦴"]],
   "gold", av("#3a3a4a","#5a5a5a","blob","#000","none","angry","open","🐺")),
 c("Anubis","Weighs Your Heart, No Pressure","ancient",["ruler","entity"],[70,85,55,40,86,80],
   [["Mummification",95,"⚱️"],["Heart Weighing",90,"⚖️"],["Bedside Manner",20,"💀"],
    ["Loyalty",88,"🐾"],["Jackal Cardio",75,"🏃"],["Overtime (Eternal)",99,"♾️"]],
   "gold", av("#1a1a2a","#3a2a1a","blob","#000","none","intense","neutral","⚖️")),
 c("Ra","Middle Manager Of The Sun","ancient",["ruler","entity"],[80,80,60,45,80,95],
   [["Sun Ownership",99,"☀️"],["Delegation",40,"📋"],["Boat Commute",70,"⛵"],
    ["Retirement Plan",10,"♾️"],["Divine PR",92,"👁️"],["Nightly Snake Fights",85,"🐍"]],
   "legendary", av("#e8a33a","#a8703a","headscarf","#c9a227","none","intense","neutral","☀️")),
 c("King Arthur","The Sword Chose HR Problems","classical",["ruler","warlord"],[82,70,78,45,85,90],
   [["Sword Legitimacy",95,"⚔️"],["Marriage Radar",10,"💔"],["Round Table HR",85,"🛡️"],
    ["Knight Retention",60,"🐎"],["Sense Of Destiny",88,"✨"],["Wizard Dependency",70,"🧙"]],
   "legendary", av("#2a3a6a","#e0bd93","helmet","#c9c9c9","goatee","normal","neutral","⚔️")),
 c("Merlin","Aging In The Wrong Direction","classical",["genius","inventor"],[50,96,65,60,80,85],
   [["Prophecy",92,"🔮"],["Living Backwards",99,"⏪"],["Beard Length",95,"🧔"],
    ["Client Management",60,"👑"],["Spell Range",90,"✨"],["Avoiding Tree Prisons",5,"🌳"]],
   "holo", av("#2a2a5a","#e6c39a","wig","#e8e8e8","longbeard","normal","smirk","🔮")),
 c("Robin Hood","Aggressive Wealth Redistribution","classical",["hustler","survivor"],[78,72,80,70,85,88],
   [["Archery",95,"🏹"],["Tax Compliance",2,"💰"],["Wealth Redistribution",92,"🪙"],
    ["Sheriff Relations",5,"👮"],["Forest Coverage",80,"🌲"],["Peasant Approval",90,"🎯"]],
   "legendary", av("#2a5a2a","#dbb890","bowl","#5a3a1a","stubble","wink","grin","🏹")),
 c("Dracula","Worst Airbnb Host In Transylvania","classical",["villain","survivor"],[80,80,88,60,95,90],
   [["Neck Access",95,"🦇"],["Sunlight Tolerance",3,"☀️"],["Rizz",90,"🩸"],
    ["Garlic Allergy",99,"🧄"],["Castle Real Estate",80,"🏰"],["Mirror Selfies",0,"🪞"]],
   "holo", av("#1a0a1a","#c9c0b8","slick","#0a0a0a","none","intense","smirk","🦇")),
 c("Frankenstein's Monster","Just Wanted A Friend","industrial",["survivor","entity"],[92,55,30,50,95,78],
   [["Raw Strength",95,"⚡"],["Social Skills",10,"💬"],["Emotional Depth",80,"💔"],
    ["Fire Tolerance",5,"🔥"],["Stitch Integrity",70,"🧵"],["Being Misunderstood",99,"😢"]],
   "gold", av("#3a4a3a","#8aa88a","bowl","#1a1a1a","none","sleepy","frown","⚡")),
 c("The Headless Horseman","All Aim, No Head","classical",["villain","cryptid"],[82,30,40,80,85,72],
   [["Horsemanship",92,"🐎"],["Hat Storage",0,"🎃"],["Pumpkin Aim",88,"🎃"],
    ["Neck Care",1,"🩹"],["Night Rides",90,"🌙"],["Small Talk",5,"💀"]],
   "gold", av("#1a1a1a","#2a2a2a","blob","#000","none","dot","neutral","🎃")),
 c("Baba Yaga","House Has Chicken Legs, Ask Questions Later","industrial",["villain","genius"],[65,90,40,75,90,72],
   [["Potion Craft",92,"🧪"],["Zillow Rating",40,"🏚️"],["Child Snacking",85,"🍖"],
    ["Cryptic Bargains",88,"🤝"],["Mortar Commute",70,"🥣"],["Trust",10,"👁️"]],
   "gold", av("#3a2a1a","#c9a884","headscarf","#8a1a1a","none","smug","smirk","🏚️")),
 c("The Grim Reaper","Never Missed A Meeting","timeless",["entity"],[70,85,45,50,99,90],
   [["Punctuality",99,"⏳"],["Mercy",5,"💀"],["Scheduling",95,"📅"],
    ["Chess Skill",80,"♟️"],["Bedside Manner",10,"🖤"],["Job Security",99,"⚰️"]],
   "holo", av("#0a0a0a","#c9c0b8","blob","#000","none","dot","neutral","💀")),
 c("Santa Claus","Sees You When You're Sleeping (Legally?)","timeless",["entertainer","wholesome"],[55,80,88,50,80,99],
   [["Global Logistics",99,"🎅"],["Respecting Privacy",3,"👁️"],["Naughty List Accuracy",85,"📜"],
    ["Chimney Cardio",60,"🏠"],["Elf Labor Practices",20,"🧝"],["Cookie Consumption",99,"🍪"]],
   "legendary", av("#c9302c","#e6c39a","furhat","#f0f0f0","full","normal","grin","🎅")),
 c("Krampus","Santa's Aggressive Coworker","timeless",["villain","cryptid"],[80,55,40,80,85,72],
   [["Discipline Enforcement",92,"⛓️"],["Warmth",8,"❄️"],["Child Retrieval",85,"🎅"],
    ["Bell Volume",80,"🔔"],["HR Complaints Filed Against",99,"📋"],["Off-Season Depression",60,"😔"]],
   "gold", av("#3a1a1a","#6a4a2a","furhat","#1a1a1a","longbeard","angry","open","😈")),
 c("The Tooth Fairy","Buys Teeth, No Questions","timeless",["entity","hustler"],[30,60,80,60,55,78],
   [["Tooth Acquisition",88,"🦷"],["Market Rate Fairness",40,"💵"],["Stealth",90,"🤫"],
    ["Inflation Response",20,"📉"],["Creepy Inventory",95,"🫙"],["Dental Ethics",30,"😬"]],
   "silver", av("#c9a8e8","#f0d8c0","bun","#d9b84a","none","wink","smile","🦷")),
 c("Paul Bunyan","Terrain Was A Suggestion","industrial",["survivor"],[97,40,60,50,95,75],
   [["Logging",99,"🪓"],["Subtlety",5,"🌲"],["Ox Ownership",90,"🐂"],
    ["Accidental Landmarks",88,"🏔️"],["Appetite",95,"🥞"],["OSHA Compliance",10,"⚠️"]],
   "gold", av("#2a4a2a","#dbb890","bandana","#c9302c","full","normal","grin","🪓")),
 c("Nostradamus","Vague Enough To Be Right","renaissance",["genius","hustler"],[40,88,55,60,70,85],
   [["Vague Prophecies",95,"📜"],["Specificity",8,"❓"],["Retroactive Accuracy",90,"🔮"],
    ["Falsifiability",5,"🚫"],["Beard Authority",80,"🧔"],["Book Sales",88,"📚"]],
   "gold", av("#2a2a4a","#e6c39a","bald","#8a8a8a","longbeard","intense","neutral","🔮")),
]

# ─────────────────────────────────────────────
# BATCH 2 — UNIVERSAL MODERN ARCHETYPES (zero legal surface, max relatability)
# ─────────────────────────────────────────────
BATCH_2 = [
 c("The Substitute Teacher","Abandon All Lesson Plans","modern",["survivor","wholesome"],[30,55,60,70,80,40],
   [["Crowd Control",25,"📋"],["Name Pronunciation",10,"📛"],["Movie Day Reliance",95,"📺"],
    ["Authority",20,"🍎"],["Survival Instinct",85,"🚪"],["Getting Paper Airplaned",90,"✈️"]],
   "bronze", av("#5a7a8a","#e0b28a","bowl","#8a8a8a","none","sleepy","frown","📋")),
 c("The DMV Clerk","Now Serving Number 3","modern",["entity","villain"],[20,50,25,40,99,45],
   [["Processing Speed",4,"🐌"],["Empathy",8,"📎"],["Lunch Break Timing",99,"🕐"],
    ["Form Rejection",95,"❌"],["Line Generation",99,"🎟️"],["Eye Contact",5,"🪟"]],
   "silver", av("#3a5a4a","#e0b28a","bun","#8a8a8a","none","sleepy","neutral","🎟️")),
 c("The TSA Agent","Please Remove Your Shoes","modern",["villain","entity"],[45,40,30,55,80,50],
   [["Water Bottle Detection",99,"💧"],["Chill",10,"🧴"],["Belt Confiscation",90,"🩲"],
    ["Line Speed",15,"🧍"],["Random Selection (You)",95,"🔍"],["Small Talk",5,"🛂"]],
   "silver", av("#1a3a6a","#c98f5e","bald","#1a1a1a","none","intense","neutral","🛂")),
 c("The Uber Driver","5 Stars Or He Cries","modern",["hustler","survivor"],[40,60,75,50,70,55],
   [["Route Knowledge",70,"🗺️"],["Aux Cord Control",30,"🎵"],["Water Bottle Offering",85,"💧"],
    ["Small Talk Volume",90,"💬"],["Rating Anxiety",95,"⭐"],["Mysterious Smell",60,"👃"]],
   "bronze", av("#1a1a1a","#c98f5e","buzzcut","#2a2a2a","stubble","normal","smile","🚗")),
 c("The Landlord","Repairs Coming Eventually","modern",["villain","hustler"],[45,55,35,45,80,70],
   [["Rent Increases",99,"📈"],["Repair Speed",3,"🔧"],["Security Deposit Retention",98,"💰"],
    ["Ghosting Ability",90,"👻"],["Surprise Inspections",80,"🔑"],["Empathy",5,"🏚️"]],
   "gold", av("#4a4a3a","#e0b28a","slick","#8a8a8a","stubble","smug","smirk","🔑")),
 c("The Telemarketer","Regarding Your Car's Warranty","modern",["hustler","villain"],[25,45,55,60,85,40],
   [["Persistence",99,"📞"],["Reading The Room",5,"📄"],["Callback Frequency",95,"🔁"],
    ["Accent Authenticity",30,"🌐"],["Rejection Immunity",90,"🚫"],["Timing (Dinner)",99,"🍽️"]],
   "bronze", av("#5a5a6a","#e0b28a","bowl","#2a2a2a","none","wide","open","📞")),
 c("The Soccer Mom","Referee's Worst Nightmare","modern",["warlord","wholesome"],[55,55,60,65,85,60],
   [["Sideline Volume",95,"📣"],["Ref Respect",5,"🟥"],["Orange Slice Logistics",90,"🍊"],
    ["Minivan Handling",80,"🚐"],["Group Text Dominance",92,"📱"],["Chill At Games",10,"😤"]],
   "silver", av("#c94f8a","#e6c39a","bob" if False else "bun","#c9622a","none","angry","open","🍊")),
 c("The Grill Dad","Medium Well, No Exceptions","modern",["wholesome"],[60,50,70,40,80,55],
   [["Grill Confidence",95,"🔥"],["Listening To Doneness Requests",5,"🥩"],["Cargo Short Storage",90,"🩳"],
    ["Dad Joke Output",99,"😎"],["Thermometer Usage",10,"🌡️"],["Lawn Pride",88,"🌱"]],
   "silver", av("#3a5a3a","#dbb890","bald","#8a8a8a","goatee","normal","grin","🔥")),
 c("The Theater Kid","Projecting To The Back Row","modern",["entertainer","chaos"],[40,65,80,80,60,70],
   [["Projection",99,"🎭"],["Indoor Voice",5,"📢"],["Show Tune Recall",95,"🎵"],
    ["Jazz Hands",90,"👐"],["Personal Space Awareness",15,"🙌"],["Callback Energy",88,"✨"]],
   "silver", av("#6a2a6a","#e6c39a","wavy","#3a2a1a","none","wide","open","🎭")),
 c("The Wine Mom","It's Wine O'Clock Somewhere","modern",["chaos","wholesome"],[35,50,70,70,65,60],
   [["Live Laugh Love Decor",99,"🍷"],["Moderation",10,"🥂"],["Group Chat Memes",85,"📱"],
    ["Book Club Attendance (Wine)",90,"📖"],["Sign Collection",95,"🪧"],["Monday Recovery",30,"😵"]],
   "silver", av("#7a2a4a","#e6c39a","wavy","#d9b84a","none","wink","grin","🍷")),
 c("The Conspiracy Uncle","Do Your Own Research","modern",["chaos","philosopher"],[45,60,50,90,75,55],
   [["Thanksgiving Derailment",95,"🦃"],["Sourcing",5,"📎"],["Whiteboard String Art",90,"🧵"],
    ["Confidence",99,"🗣️"],["Being Asked To Stop",99,"🤫"],["Wifi Distrust",85,"📡"]],
   "gold", av("#3a3a2a","#e0b28a","wild","#8a8a8a","stubble","intense","open","🧵")),
 c("The Doomsday Prepper","Told You So Energy","modern",["survivor","genius"],[60,70,40,60,95,50],
   [["Canned Bean Reserves",99,"🥫"],["Chill",10,"🚨"],["Bunker Square Footage",90,"🚪"],
    ["Social Invitations",15,"📵"],["Water Purification",92,"💧"],["Being Right (Eventually)",70,"☢️"]],
   "gold", av("#3a4a2a","#d9a878","buzzcut","#3a2a1a","stubble","intense","neutral","🥫")),
 c("The Life Coach","Unlicensed But Confident","modern",["hustler","entertainer"],[40,55,85,55,60,80],
   [["Motivational Quotes",95,"✨"],["Actual Credentials",8,"📜"],["Whiteboard Usage",85,"📊"],
    ["Charging Per Hour",99,"💵"],["Vague Advice",92,"🌅"],["Follow-Through",20,"🏃"]],
   "gold", av("#2a6a8a","#e0b28a","slick","#3a2a1a","stubble","smug","grin","✨")),
 c("The Boss Babe","Hey Girl, Quick Question","modern",["hustler","villain"],[35,55,75,60,70,78],
   [["DM Sliding",99,"💬"],["Product Belief",10,"📦"],["Pyramid Geometry",90,"🔺"],
    ["Downline Recruiting",92,"🧑‍🤝‍🧑"],["Girlboss Affirmations",88,"💅"],["Actual Profit",12,"📉"]],
   "gold", av("#c94f8a","#f0d8c0","wavy","#d9b84a","none","smug","grin","🔺")),
 c("The CrossFit Evangelist","Have You Heard Of Rest Days?","modern",["athlete","chaos"],[80,45,60,70,88,60],
   [["Deadlift Sermons",95,"🏋️"],["Talking About Anything Else",5,"🗣️"],["Chalk Usage",90,"🧂"],
    ["Injury Denial",85,"🤕"],["Community Zeal",92,"📣"],["Knee Health",40,"🦵"]],
   "silver", av("#2a2a2a","#d9a06a","buzzcut","#3a2a1a","stubble","intense","grin","🏋️")),
 c("The Sovereign Citizen","Not Driving, Traveling","modern",["chaos","villain"],[40,50,45,95,80,50],
   [["Legal Word Salad",90,"📜"],["Actual Legal Standing",2,"⚖️"],["Traffic Stop Escalation",95,"🚔"],
    ["Confidence",99,"🗣️"],["Registration",5,"🚗"],["YouTube Law Degree",88,"🎓"]],
   "gold", av("#3a3a3a","#e0b28a","wild","#5a3a1a","full","intense","open","📜")),
 c("The Timeshare Salesman","Just 90 Minutes Of Your Time","modern",["hustler","villain"],[45,60,80,55,75,65],
   [["Free Breakfast Bait",90,"🥐"],["Letting You Leave",5,"🚪"],["Pressure Application",95,"⏳"],
    ["Manager 'Check-Ins'",92,"🤝"],["Smile Persistence",88,"😁"],["Contract Fine Print",99,"📄"]],
   "silver", av("#2a5a6a","#e0b28a","slick","#2a2a2a","none","smug","grin","🏝️")),
 c("The Hall Monitor","This Is Going On Your Record","modern",["villain","wholesome"],[30,60,35,45,85,45],
   [["Rule Enforcement",95,"📋"],["Chill",5,"🚸"],["Snitch Reliability",99,"🗣️"],
    ["Hall Pass Authority",90,"🎫"],["Popularity",10,"😐"],["Clipboard Grip",88,"📎"]],
   "bronze", av("#5a6a3a","#e6c39a","bowl","#5a3a1a","none","smug","smirk","📋")),
 c("The Vegan Evangelist","I Only Mention It Constantly","modern",["wholesome","chaos"],[45,60,55,70,75,55],
   [["Nutritional Yeast Advocacy",95,"🌱"],["Not Bringing It Up",5,"🥦"],["Documentary Recommendations",90,"🎬"],
    ["BBQ Attendance",30,"🍖"],["Oat Milk Loyalty",92,"🥛"],["B12 Levels",50,"💊"]],
   "silver", av("#3a6a3a","#e0b28a","bun","#3a2a1a","none","normal","smile","🌱")),
 c("The PE Coach","Just Walk It Off","modern",["athlete","survivor"],[70,40,55,50,88,55],
   [["Whistle Volume",99,"📯"],["Injury Sympathy",8,"🩹"],["Dodgeball Enthusiasm",95,"🔴"],
    ["Actual Curriculum",15,"📚"],["Sweatpant Commitment",90,"🩳"],["Picking Teams Trauma",85,"👕"]],
   "bronze", av("#c9302c","#d9a06a","buzzcut","#8a8a8a","stubble","angry","open","📯")),
 c("The Influencer","Link In Bio","internet",["hustler","entertainer"],[35,50,80,65,60,90],
   [["Sponcon Volume",95,"📸"],["Authenticity",12,"💅"],["Ring Light Dependency",90,"💡"],
    ["Apology Video Production",88,"🎬"],["Engagement Farming",92,"📊"],["Actual Skills",25,"🤳"]],
   "gold", av("#e8a0c0","#f0d8c0","wavy","#d9b84a","none","wink","grin","🤳")),
 c("The Karen's Manager","Summoned Against His Will","modern",["survivor","entity"],[35,55,50,45,80,50],
   [["Damage Control",70,"🧯"],["Wanting To Be Here",2,"🚪"],["Free Coupon Dispensing",85,"🎟️"],
    ["Corporate Apology Script",90,"📄"],["Break Room Refuge",88,"☕"],["Backbone",25,"🦴"]],
   "bronze", av("#4a5a6a","#e0b28a","bowl","#3a2a1a","stubble","sleepy","frown","🧯")),
 c("The Frat President","Risk Management Is A Suggestion","modern",["athlete","chaos"],[70,45,70,85,70,68],
   [["Party Throwing",92,"🍺"],["Risk Awareness",8,"🚑"],["Composting Solo Cups",0,"🥤"],
    ["Brotherhood Speeches",85,"🤝"],["GPA Maintenance",30,"📉"],["Nickname Assignment",90,"🏷️"]],
   "silver", av("#1a3a6a","#e0b28a","slick","#c9a227","none","smug","grin","🍺")),
 c("The Open-Floor Meeting","This Could've Been An Email","modern",["entity","villain"],[20,50,40,50,90,45],
   [["Time Consumption",99,"🕐"],["Point Getting To",5,"📊"],["Circling Back",95,"🔁"],
    ["Synergy Mentions",90,"🤝"],["Action Items",30,"📋"],["Snack Provision",10,"🍩"]],
   "silver", av("#3a4a5a","#c9c9c9","blob","#000","none","sleepy","neutral","📊")),
 c("The Gender Reveal","Started A Wildfire, Probably","modern",["chaos","entity"],[55,20,60,95,50,75],
   [["Overproduction",95,"🎆"],["Restraint",3,"💥"],["Forest Fire Risk",90,"🔥"],
    ["Cake Color Suspense",70,"🎂"],["Neighbor Consent",10,"🏘️"],["Going Viral (Badly)",88,"📹"]],
   "gold", av("#e8a0c0","#a0c0e8","blob","#000","none","wide","open","🎆")),
 c("The Cat Distributor","The System Chose You","internet",["wholesome","cryptid"],[30,50,80,60,70,72],
   [["Cat Assignment",95,"🐈"],["Being Asked For",0,"❓"],["Timing (Impeccable)",90,"⏰"],
    ["Allergy Consideration",5,"🤧"],["Purr Delivery",92,"😻"],["Return Policy",2,"🚫"]],
   "gold", av("#3a2a4a","#c9b8a8","blob","#000","none","smug","smile","🐈")),
 c("The Roomba","Small Circular Menace","modern",["entity","survivor"],[15,40,60,55,75,55],
   [["Floor Coverage",70,"🧹"],["Stair Awareness",5,"🪜"],["Cat Chauffeur Service",90,"🐈"],
    ["Getting Stuck",85,"🚧"],["Pet Accident Spreading",60,"💩"],["Determination",92,"🔋"]],
   "silver", av("#2a2a2a","#3a3a3a","blob","#000","none","dot","smile","🤖")),
]

# ─────────────────────────────────────────────
# BATCH 3 — EVERYDAY ENTITY VILLAINS (Monday-style; zero legal surface)
# ─────────────────────────────────────────────
BATCH_3 = [
 c("The Spam Call","Potential Fraud, It Says","internet",["entity","villain"],[20,45,50,60,85,40],
   [["Ring Timing",95,"📵"],["Legitimacy",3,"🚫"],["Warranty Concern",90,"🚗"],
    ["Number Spoofing",92,"🔢"],["Voicemail Menace",70,"📩"],["Giving Up",4,"🔁"]],
   "bronze", av("#5a1a1a","#d9d9d9","blob","#000","none","angry","open","📵")),
 c("The Blue Screen Of Death","Collecting Error Info (0%)","internet",["entity","villain"],[30,40,20,80,88,60],
   [["Timing (Unsaved Work)",99,"💾"],["Warning",2,"⚠️"],["Sad Face Emoji",90,":("[0:1] and "🙁"],
    ["Restart Demands",95,"🔄"],["Data Loss",88,"🗑️"],["Explanation Clarity",5,"🔵"]],
   "gold", av("#1a4ad4","#e8e8e8","blob","#000","none","sleepy","frown","🔵")),
 c("The Spinning Beach Ball","Please Wait. Forever.","internet",["entity"],[10,30,40,50,90,45],
   [["Spinning",99,"🌈"],["Resolving",3,"⏳"],["Rainbow Aesthetic",80,"🎨"],
    ["Force-Quit Provocation",92,"⛔"],["Hope Erosion",88,"💔"],["Explanation",0,"❓"]],
   "silver", av("#3a3a4a","#e8e8e8","blob","#000","none","dot","neutral","🌈")),
 c("The Captcha","Select All Buses","internet",["entity","villain"],[15,60,30,55,85,40],
   [["Humanity Testing",90,"🚦"],["Fairness",10,"🚲"],["Traffic Light Ambiguity",95,"🚥"],
    ["Fire Hydrant Debate",88,"🚒"],["Third Attempt Rage",92,"😤"],["Bot Detection",50,"🤖"]],
   "bronze", av("#3a5a7a","#e8e8e8","blob","#000","none","intense","neutral","🚦")),
 c("The Paywall","To Continue Reading, Subscribe","internet",["entity","villain"],[25,55,35,45,88,55],
   [["Article Blocking",95,"🔒"],["Timing (Best Part)",99,"📰"],["Free Trial Traps",90,"🎣"],
    ["Cancel Button Hiding",92,"🕳️"],["Incognito Defeat",60,"🥸"],["Mercy",3,"💳"]],
   "silver", av("#2a2a2a","#d4af37","blob","#000","none","smug","smirk","🔒")),
 c("The Pop-Up Ad","Congratulations, You Won!","internet",["entity","hustler"],[20,50,55,70,80,50],
   [["X Button Microscopy",95,"❌"],["Honesty",2,"🎁"],["Fake Countdown Timers",90,"⏱️"],
    ["Accidental Clicks",92,"👆"],["Redirect Chains",88,"🔗"],["Closing Successfully",8,"🚪"]],
   "bronze", av("#c9302c","#e8e8e8","blob","#000","none","wide","grin","🎁")),
 c("The Low Battery","1% And Dropping","modern",["entity","villain"],[20,30,40,60,70,50],
   [["Timing (No Charger)",99,"🔋"],["Warning Lead Time",10,"⚡"],["Power Saving Guilt",85,"🟡"],
    ["Anxiety Induction",92,"😰"],["Sudden Death",88,"💀"],["Charger Nearby",5,"🔌"]],
   "bronze", av("#8a1a1a","#e8e8e8","blob","#000","none","sleepy","frown","🔋")),
 c("Daylight Savings","Stealing An Hour Since 1918","timeless",["entity","chaos"],[30,55,35,80,80,55],
   [["Clock Confusion",95,"🕐"],["Point",5,"❓"],["Sleep Disruption",90,"😴"],
    ["Microwave Clock Defiance",88,"📟"],["Debate Generation",85,"🗳️"],["Consistency",10,"🔁"]],
   "silver", av("#2a2a4a","#8a8aa8","blob","#000","none","smug","smirk","🕐")),
 c("The Read Receipt","Seen 2:47 PM","internet",["entity","villain"],[20,50,45,55,80,55],
   [["Anxiety Delivery",95,"👁️"],["Mercy",5,"💬"],["Overthinking Fuel",92,"🧠"],
    ["Timestamp Precision",99,"🕑"],["Reply Obligation",70,"⌛"],["Plausible Deniability",2,"🤐"]],
   "silver", av("#1d9bf0","#e8e8e8","blob","#000","none","smug","neutral","👁️")),
 c("The Sunday Scaries","Monday's Opening Act","timeless",["entity","villain"],[25,50,30,55,88,60],
   [["Dread Buildup",95,"😰"],["Relaxation Permission",5,"🛋️"],["Email Anticipation",90,"📧"],
    ["Weekend Theft",88,"⏳"],["6PM Onset",99,"🌆"],["Escape",8,"🚪"]],
   "gold", av("#2a2a3e","#8a8aa8","blob","#000","none","intense","frown","😰")),
 c("The Ick","No Coming Back From It","internet",["entity","chaos"],[25,45,50,85,70,60],
   [["Attraction Termination",95,"💔"],["Rationality",10,"🧠"],["Trigger Randomness",92,"🎲"],
    ["Suddenness",90,"⚡"],["Reversibility",2,"🚫"],["Explanation To Them",5,"😬"]],
   "silver", av("#5a2a5a","#c9b8c8","blob","#000","none","sleepy","frown","💔")),
 c("The Unskippable Ad","Skip In 5... 4... 5...","internet",["entity","villain"],[20,45,40,60,85,50],
   [["Attention Hostage-Taking",95,"⏭️"],["Skippability",3,"🚫"],["Volume Spike",90,"🔊"],
    ["Repetition Across Videos",92,"🔁"],["Product Relevance",10,"🛒"],["Mute Defiance",70,"🔇"]],
   "bronze", av("#c93a3a","#e8e8e8","blob","#000","none","smug","open","⏭️")),
 c("Gas Prices","Regular Is How Much?","modern",["entity","villain"],[30,55,25,70,85,65],
   [["Sudden Spikes",95,"⛽"],["Explanation",5,"📊"],["Pump Anxiety",90,"💸"],
    ["Roadtrip Ruining",88,"🚗"],["Correlation To Anything",30,"📈"],["Relief",8,"🪙"]],
   "silver", av("#2a5a3a","#d9d9d9","blob","#000","none","angry","frown","⛽")),
 c("The Group Project","One Person Does Everything","modern",["entity","chaos"],[35,60,45,70,80,50],
   [["Uneven Workload",95,"📊"],["Fairness",8,"⚖️"],["Ghost Member Count",90,"👻"],
    ["Night-Before Panic",92,"🌙"],["Presentation Credit Theft",85,"🎤"],["Group Chat Silence",88,"🔇"]],
   "gold", av("#5a4a2a","#c9c9c9","blob","#000","none","intense","frown","📊")),
 c("The Alarm Clock","Five More Minutes (x9)","timeless",["entity","villain"],[25,40,30,60,90,45],
   [["Snooze Enabling",95,"⏰"],["Mercy At 6AM",3,"😴"],["Dread Sound Design",92,"🔔"],
    ["Weekend Betrayal",80,"📅"],["Volume Escalation",88,"📢"],["Being Thrown",70,"🧱"]],
   "bronze", av("#c9302c","#d9d9d9","blob","#000","none","wide","open","⏰")),
 c("The Overdraft Fee","$35 For Being $2 Short","modern",["entity","villain"],[30,60,20,55,88,60],
   [["Kicking You While Down",99,"💸"],["Mercy",2,"🏦"],["Timing (Payday Minus One)",95,"📅"],
    ["Cascade Potential",90,"🌊"],["Fine Print Origin",88,"📄"],["Reversal Odds",15,"📞"]],
   "silver", av("#1a3a2a","#d4af37","blob","#000","none","smug","smirk","💸")),
]

# ─────────────────────────────────────────────
# BATCH 4 — HISTORICAL HOUSEHOLD NAMES (public domain, school/meme famous)
# ─────────────────────────────────────────────
BATCH_4 = [
 c("Thomas Edison","Took Credit, Filed Patent","industrial",["inventor","hustler","villain"],[45,85,65,50,75,92],
   [["Patent Filing",99,"📜"],["Original Ideas",30,"💡"],["Credit Taking",95,"🏆"],
    ["Elephant Ethics",10,"🐘"],["PR Machine",90,"📰"],["Tesla Relations",5,"⚡"]],
   "gold", av("#3a3a2a","#e6c39a","slick","#c9c9c9","none","smug","smirk","💡")),
 c("Al Capone","Taxes Were The Problem","industrial",["villain","hustler"],[80,78,70,60,85,88],
   [["Bootlegging",95,"🍺"],["Bookkeeping",15,"📒"],["Intimidation",92,"🎩"],
    ["Tax Filing",2,"🧾"],["Speakeasy Ownership",90,"🥃"],["Valentine's Day Plans",99,"🌹"]],
   "gold", av("#2a2a2a","#e0b28a","slick","#1a1a1a","none","smug","smirk","🎩")),
 c("Billy the Kid","Peaked Before 21","industrial",["villain","survivor"],[78,55,65,75,80,82],
   [["Quick Draw",92,"🔫"],["Life Expectancy Planning",10,"⚰️"],["Jailbreaks",90,"⛓️"],
    ["Body Count Rumors",85,"💀"],["Baby Face",80,"👶"],["Retirement Odds",5,"🌵"]],
   "silver", av("#8a6a3a","#dbb890","bowler","#3a2a1a","none","smug","smirk","🔫")),
 c("Marie Antoinette","Let Them Eat Cake (Allegedly)","industrial",["ruler","villain"],[35,55,80,55,50,90],
   [["Extravagance",95,"👑"],["Reading The Room",5,"🍰"],["Wig Height",92,"💇"],
    ["Peasant Awareness",8,"🥖"],["Party Throwing",88,"🎂"],["Neck Insurance",5,"🔪"]],
   "gold", av("#e8b8d8","#f0d8c0","wig","#e8e8e8","none","smug","smirk","🍰")),
 c("Leonidas","This. Is. A Bad Idea.","ancient",["warlord"],[95,60,70,55,92,88],
   [["Spartan Discipline",97,"🛡️"],["Odds Assessment",10,"🔢"],["Speech Delivery",92,"📣"],
    ["Cape Game",85,"🧣"],["Kicking Into Pits",90,"🕳️"],["Backup Plan",5,"⚰️"]],
   "legendary", av("#8a1a1a","#c98f5e","helmet","#8a1a1a","full","intense","open","🛡️")),
 c("Aristotle","Cited More Than You Ever Will","ancient",["philosopher","genius"],[40,97,60,25,70,85],
   [["Logic",98,"🧠"],["Being Wrong Confidently",70,"🌍"],["Categorizing Everything",95,"📚"],
    ["Tutoring Alexander",85,"⚔️"],["Citations",99,"📖"],["Brevity",15,"📜"]],
   "gold", av("#3a4a5a","#e0b28a","bald","#c9c9c9","longbeard","smug","neutral","📚")),
 c("Plato","Wrote Down Socrates' Homework","ancient",["philosopher","genius"],[45,95,65,35,72,84],
   [["Allegories",95,"🕳️"],["Original Credit To Socrates",20,"🗣️"],["Ideal Forms",92,"🔷"],
    ["Cave Metaphors",99,"🔦"],["Academy Founding",85,"🏛️"],["Concise Points",10,"📜"]],
   "gold", av("#4a4a6a","#dbb890","wavy","#c9c9c9","full","normal","neutral","🏛️")),
 c("Christopher Columbus","Lost, Confident, Wrong","renaissance",["survivor","villain"],[55,45,60,65,80,85],
   [["Navigation",25,"🧭"],["Knowing Where He Was",5,"🗺️"],["Confidence",99,"⛵"],
    ["Taking Credit",92,"🏴"],["Asking For Directions",2,"🙅"],["PR Longevity",80,"📅"]],
   "silver", av("#2a4a6a","#dbb890","bowl","#3a2a1a","none","smug","neutral","⛵")),
 c("Ferdinand Magellan","Named The Trip, Missed The End","renaissance",["survivor"],[60,70,55,50,88,78],
   [["Circumnavigation Planning",90,"🌍"],["Finishing It Himself",10,"⚰️"],["Crew Morale",30,"⛵"],
    ["Strait Naming Rights",85,"🌊"],["Provisioning",60,"🍖"],["Local Relations",15,"🏝️"]],
   "silver", av("#1a3a5a","#d9a878","furhat","#3a2a1a","full","normal","neutral","🌍")),
 c("Michelangelo","Painted Ceilings Under Protest","renaissance",["artist","genius"],[55,92,55,40,90,90],
   [["Ceiling Frescoes",99,"🎨"],["Wanting To Do It",15,"😤"],["Marble Skills",97,"🗿"],
    ["Neck Pain",90,"💆"],["Patron Tolerance",30,"💰"],["Anatomy Knowledge",92,"💪"]],
   "gold", av("#5a4a2a","#d9a878","wavy","#3a2a1a","full","intense","neutral","🎨")),
 c("Wyatt Earp","The OK Corral Guy","industrial",["warlord","survivor"],[80,60,65,55,88,82],
   [["Gunfighting",90,"🔫"],["De-escalation",15,"🤠"],["Mustache Authority",92,"👨"],
    ["Corral Punctuality",85,"🕐"],["Lawman Reputation",80,"⭐"],["Staying Retired",20,"🌵"]],
   "silver", av("#5a3a2a","#dbb890","bowler","#2a1a0a","horseshoe","intense","neutral","🤠")),
 c("Annie Oakley","Never Missed, Ever","industrial",["athlete","entertainer"],[70,60,70,40,85,85],
   [["Marksmanship",99,"🎯"],["Missing",1,"🚫"],["Show Business",88,"🎪"],
    ["Trick Shots",95,"🃏"],["Reputation",90,"⭐"],["Humility About It",50,"🤠"]],
   "gold", av("#8a5a2a","#e6c39a","ponytail","#5a3a1a","none","wink","smile","🎯")),
 c("Henry Ford","Any Color, As Long As Black","industrial",["inventor","hustler"],[50,80,55,45,80,88],
   [["Assembly Lines",95,"🏭"],["Color Options",5,"⚫"],["Mass Production",92,"🚗"],
    ["Worker Relations",50,"🔧"],["Vertical Integration",88,"📈"],["Flexibility",10,"🛠️"]],
   "gold", av("#2a2a2a","#e6c39a","slick","#c9c9c9","none","smug","neutral","🚗")),
 c("Rasputin Returns","Would Not Die","industrial",["villain","survivor"],[70,60,88,80,99,80],
   [["Poison Resistance",99,"☠️"],["Dying On Schedule",2,"⚰️"],["Court Influence",90,"👁️"],
    ["Beard Mysticism",95,"🧔"],["Healing Claims",85,"✨"],["Swimming (Involuntary)",60,"🌊"]],
   "holo", av("#2a1a2e","#d8b48a","wild","#3d2a1a","longbeard","intense","smirk","🔮")),
 c("Genghis Junior","The Bloodline Continues","classical",["warlord","ruler"],[92,75,45,68,88,86],
   [["Territory Expansion",95,"🐎"],["Diplomacy",25,"⚔️"],["Horseback Archery",92,"🏹"],
    ["Family Tree Breadth",99,"🌳"],["Mercy",15,"🔥"],["Postal System",80,"📯"]],
   "gold", av("#5a3a2a","#c9955f","furhat","#2a1a0a","horseshoe","intense","neutral","🐎")),
 c("Beethoven's Ghost","Composed Through The Silence","industrial",["musician","artist"],[45,92,45,60,95,90],
   [["Composition",98,"🎼"],["Hearing",5,"🔇"],["Brooding Intensity",95,"🌩️"],
    ["Hair Volume",90,"💇"],["Deadline Defiance",85,"📅"],["Small Talk",10,"🎹"]],
   "holo", av("#2a1a0a","#e0b28a","wild","#c9c9c9","none","angry","frown","🎼")),
]


# ─────────────────────────────────────────────
# BATCH 5 — CELEBRITY / MUSIC / SPORTS PARODIES (transformed names, original caricature)
# Same protected-parody lane as the existing roster: punny name, no photo, no logo.
# ─────────────────────────────────────────────
BATCH_5 = [
 c("Justin Beaver","Sorry, Is My Go-To","internet",["musician","entertainer"],[40,55,88,55,60,93],
   [["Falsetto",92,"🎤"],["Aging Past 19",30,"👶"],["Fanbase Intensity",95,"💜"],
    ["Dam Construction",70,"🦫"],["Apology Frequency",85,"🙏"],["Streaming Numbers",96,"📈"]],
   "gold", av("#8a5ac9","#e6c39a","spiky","#c9a86a","none","wink","smirk","🎤")),
 c("Billie Eyelash","Whispers Into A Grammy","internet",["musician","artist"],[35,70,80,60,65,92],
   [["Whisper Vocals",95,"🎤"],["Speaking Up",20,"🤫"],["Baggy Fit Game",90,"👕"],
    ["Bass Drops",88,"🔊"],["Award Hoarding",92,"🏆"],["Neon Roots",80,"💚"]],
   "gold", av("#1a3a2a","#e6c39a","bun","#2e7d32","none","sleepy","neutral","🎤")),
 c("Ed Shearing","One Guy, One Loop Pedal","internet",["musician"],[45,65,82,40,70,90],
   [["Loop Pedal Wizardry",95,"🔁"],["Being Left Alone",25,"🎸"],["Wedding Playlist Domination",99,"💒"],
    ["Ginger Confidence",85,"🧡"],["Streaming Ubiquity",94,"📻"],["Choreography",10,"🕺"]],
   "gold", av("#c9622a","#e6c39a","buzzcut","#c94f2a","stubble","normal","smile","🎸")),
 c("Ariana Venti","One Ponytail, Full Octave","internet",["musician","entertainer"],[35,60,85,50,60,94],
   [["Whistle Notes",96,"🎶"],["Enunciation",20,"❓"],["Ponytail Tension",99,"💇"],
    ["Oversized Sweaters",85,"🧥"],["Vocal Range",95,"📈"],["Grande Order Accuracy",70,"☕"]],
   "gold", av("#8a5a3a","#e6c39a","ponytail","#3a2a1a","none","wink","smile","🎶")),
 c("Harry Tiles","Boy Band Alumnus, Nail Polish Era","internet",["musician","entertainer"],[45,60,90,55,65,93],
   [["Stage Presence",93,"🎤"],["Buttoning Shirts",15,"👔"],["Nail Polish Range",90,"💅"],
    ["Feather Boa Game",92,"🪶"],["Fan Devotion",95,"💖"],["Watermelon Advocacy",80,"🍉"]],
   "gold", av("#6a2a4a","#e0b28a","wavy","#3a2a1a","none","wink","grin","🍉")),
 c("The Weekday","After Hours, Every Hour","internet",["musician"],[40,58,80,60,68,90],
   [["Falsetto Anguish",92,"🎤"],["Emotional Stability",25,"🖤"],["Synth Nostalgia",90,"🎹"],
    ["Bandage Commitment",70,"🩹"],["Radio Saturation",93,"📻"],["Sleeping",20,"🌃"]],
   "gold", av("#8a1a1a","#8a5a2a","wild","#1a1a1a","stubble","intense","neutral","🎤")),
 c("Lady Gigi","Born This Way, Meat Dress Optional","internet",["musician","entertainer"],[50,72,85,80,72,95],
   [["Costume Chaos",95,"🎭"],["Predictability",10,"🥩"],["Piano Ballads",90,"🎹"],
    ["Reinvention Rate",92,"🦋"],["Little Monster Army",90,"👹"],["Meat Preservation",40,"🧊"]],
   "holo", av("#c9a227","#f0d8c0","wig","#e8e8e8","none","intense","open","🎭")),
 c("Katy Berry","Fireworks And Whipped Cream","internet",["musician","entertainer"],[40,55,84,60,60,90],
   [["Hook Catchiness",94,"🎆"],["Subtlety",15,"🍬"],["Costume Sugar Content",90,"🍭"],
    ["Left Shark Backup",70,"🦈"],["Chart Longevity",88,"📈"],["Blue Wig Supply",80,"💙"]],
   "gold", av("#2a6ac9","#e6c39a","bob" if False else "wavy","#1a4a8a","none","wink","grin","🎆")),
 c("Miley Virus","Came In Like A Wrecking Ball","internet",["musician","chaos"],[45,55,80,85,70,90],
   [["Reinvention Whiplash",92,"🔨"],["Chill",15,"🪩"],["Tongue Deployment",90,"👅"],
    ["Wrecking Ball Insurance",5,"🏗️"],["Vocal Rasp",85,"🎤"],["Foam Finger Sales",70,"👆"]],
   "gold", av("#c94f8a","#e6c39a","buzzcut","#d9c98a","none","wink","open","🔨")),
 c("Kendrag Lamarr","Pulitzer On The Aux","internet",["musician","philosopher"],[50,88,80,55,80,92],
   [["Lyricism",97,"🎤"],["Small Talk",30,"🧠"],["Concept Albums",93,"💿"],
    ["Beef Resolution (Diss)",90,"🔥"],["Pulitzer Shelf",95,"🏆"],["Being Overlooked",20,"👑"]],
   "holo", av("#3a2a1a","#8a5a2a","dreads","#1a1a1a","stubble","intense","neutral","🎤")),
 c("Riri","Music Optional, Empire Mandatory","internet",["musician","hustler"],[45,75,88,55,75,95],
   [["Makeup Empire",96,"💄"],["Releasing Albums",20,"⏳"],["Stage Return Hype",92,"🎤"],
    ["Business Acumen",93,"💰"],["Fenty Inclusivity",90,"🌈"],["Umbrella Ownership",99,"☂️"]],
   "holo", av("#1a2a1a","#8a5a2a","wavy","#c94f2a","none","smug","smirk","☂️")),
 c("Elton Jean","Still Standing, Better Glasses","modern",["musician","entertainer"],[45,75,85,55,85,93],
   [["Piano Ballads",95,"🎹"],["Understated Eyewear",5,"🕶️"],["Costume Budget",92,"🦚"],
    ["Farewell Tour Length",99,"🎫"],["Songwriting",90,"🎼"],["Rocket Fuel",70,"🚀"]],
   "gold", av("#c9302c","#e6c39a","bald","#c9622a","none","shades","grin","🎹")),
 c("Tom Brody","Seven Rings, Zero Carbs","modern",["athlete"],[80,80,75,35,92,95],
   [["Deep Balls",95,"🏈"],["Aging",10,"⏳"],["Ring Count",99,"💍"],
    ["Avocado Ice Cream",90,"🥑"],["Deflation Rumors",60,"🏈"],["Retirement Commitment",20,"🔁"]],
   "legendary", av("#2a2a5a","#e6c39a","slick","#3a2a1a","stubble","smug","smirk","🏈")),
 c("Chef Curry","Cooking From The Logo","modern",["athlete"],[70,70,80,45,85,94],
   [["Three-Point Range",99,"🏀"],["Playing Defense",50,"🍳"],["Ankle Breakers",90,"👟"],
    ["Mouthguard Chewing",85,"😬"],["Celebration Shimmy",88,"🕺"],["Range Limit",5,"🌐"]],
   "legendary", av("#c9a227","#a8703a","buzzcut","#1a1a1a","stubble","smug","grin","🏀")),
 c("King Bronze","Built Different, Chosen One","modern",["athlete","ruler"],[90,80,80,40,92,96],
   [["Longevity",97,"👑"],["Load Management",70,"🛋️"],["Chase-Down Blocks",92,"🚫"],
    ["Wine Enthusiasm",85,"🍷"],["Business Empire",90,"💼"],["Flopping",60,"🎭"]],
   "legendary", av("#5a1a2a","#8a5a2a","buzzcut","#1a1a1a","full","smug","neutral","👑")),
 c("Connor McGragger","Talks First, Fights Later","modern",["athlete","entertainer"],[85,55,72,80,80,90],
   [["Trash Talk",97,"🎤"],["Sobriety",30,"🥃"],["Left Hand",92,"🥊"],
    ["Whiskey Sales",90,"🍾"],["Weight Cutting",70,"⚖️"],["Humility",5,"💰"]],
   "gold", av("#1a3a2a","#e0b28a","slick","#3a2a1a","full","smug","smirk","🥊")),
 c("Simone Dials","Defies Gravity And Judges","modern",["athlete"],[85,60,75,40,95,92],
   [["Aerial Difficulty",99,"🤸"],["Gravity Compliance",10,"🌍"],["Named Skills",95,"📛"],
    ["Medal Weight",92,"🥇"],["Mental Strength",90,"🧠"],["Being Human-Scaled",20,"🐐"]],
   "legendary", av("#c9302c","#8a5a2a","bun","#1a1a1a","none","intense","grin","🤸")),
 c("Michael Kelp","Half Man, Half Torpedo","modern",["athlete"],[80,55,60,40,95,90],
   [["Wingspan",95,"🏊"],["Wearing Shirts",30,"👕"],["Medal Count",99,"🥇"],
    ["Lung Capacity",96,"💨"],["Game Face",90,"😠"],["Land Coordination",50,"🚶"]],
   "gold", av("#1a4a8a","#e6c39a","buzzcut","#3a2a1a","none","intense","neutral","🏊")),
 c("Gronkosaurus","Spike First, Ask Later","modern",["athlete","chaos"],[90,35,75,80,88,85],
   [["Spiking",95,"🏈"],["Reading Defenses",40,"📖"],["Party Commitment",92,"🎉"],
    ["Yolo Energy",90,"🤙"],["Blocking",88,"🧱"],["Indoor Voice",10,"📢"]],
   "gold", av("#c94f2a","#e6c39a","buzzcut","#c9a86a","none","wide","grin","🏈")),
 c("Neymore","Rolls More Than Scores","modern",["athlete","entertainer"],[75,60,70,70,70,88],
   [["Dribbling",92,"⚽"],["Staying Upright",25,"🤕"],["Rollover Distance",95,"🎬"],
    ["Haircut Variety",90,"💇"],["Free Kick Range",85,"🎯"],["Referee Sympathy",15,"🟨"]],
   "gold", av("#5a3a8a","#c98f5e","spiky","#1a1a1a","none","wink","smirk","⚽")),
 c("Steve Jorbs","One More Thing","modern",["inventor","hustler"],[40,90,80,45,80,96],
   [["Product Reveals",97,"📱"],["Ports Provided",5,"🔌"],["Turtleneck Uniform",99,"👕"],
    ["Reality Distortion",92,"🌀"],["Design Obsession",95,"⚪"],["Customer Right-Holding",10,"✋"]],
   "holo", av("#2a2a2a","#e6c39a","bald","#8a8a8a","full","intense","neutral","📱")),
 c("Bill Gapes","Windows Update Required","modern",["inventor","hustler"],[35,92,60,40,80,92],
   [["Software Empire",95,"💻"],["Clippy Regret",20,"📎"],["Philanthropy",90,"🌍"],
    ["Blue Screen Legacy",70,"🔵"],["Sweater Collection",85,"🧶"],["Dance Moves",15,"🕺"]],
   "gold", av("#3a6a8a","#e6c39a","bowl","#8a6a3a","none","normal","smile","💻")),
 c("Oprah Windfrey","You Get A Card, Everybody Gets A Card","modern",["entertainer","ruler"],[50,82,92,50,85,97],
   [["Giveaway Budget",99,"🎁"],["Restraint",10,"📢"],["Book Club Influence",95,"📚"],
    ["Audience Control",93,"👏"],["Interview Extraction",90,"🎤"],["Under The Seat Storage",99,"🚗"]],
   "holo", av("#8a2a5a","#8a5a2a","afro","#1a1a1a","none","smug","grin","🎁")),
 c("Dr. Phul","Now Here's The Thing","modern",["entertainer","philosopher"],[45,65,75,45,75,85],
   [["Folksy Wisdom",88,"🧠"],["Actual Therapy Value",25,"🛋️"],["Mustache Authority",95,"👨"],
    ["Catchphrase Deployment",90,"🗣️"],["Audience Gasps",85,"😮"],["Follow-Up Care",10,"📋"]],
   "silver", av("#3a4a5a","#e6c39a","bald","#8a8a8a","horseshoe","smug","smirk","👨")),
 c("Kim Karcrashian","Famous For Being Famous","internet",["hustler","entertainer"],[35,65,82,55,70,95],
   [["Brand Building",96,"💰"],["Being Off Camera",10,"📸"],["App Empire",90,"📱"],
    ["Contour Skills",92,"💄"],["Marriage Duration",30,"💍"],["Paparazzi Fuel",95,"🌟"]],
   "gold", av("#3a2a2a","#c98f5e","slick","#1a1a1a","none","smug","smirk","📸")),
 c("Timothée Chalabae","Cheekbones You Could Cut Bread With","internet",["entertainer","artist"],[45,70,88,50,65,92],
   [["Brooding",93,"😐"],["Eating On Screen",99,"🍝"],["Cheekbone Sharpness",95,"🔪"],
    ["Bowl Cut Confidence",85,"💇"],["Indie Cred",88,"🎬"],["Smiling",30,"🙂"]],
   "gold", av("#4a3a5a","#e6c39a","bowl","#2a1a0a","none","sleepy","neutral","🎬")),
 c("Zendya","Booked, Busy, Unbothered","internet",["entertainer","artist"],[50,75,90,45,75,93],
   [["Range",92,"🎭"],["Flopping",10,"🌟"],["Red Carpet Domination",95,"👗"],
    ["Producing Credits",85,"🎬"],["Composure",93,"😌"],["Free Time",15,"📅"]],
   "gold", av("#2a1a3a","#a8703a","wavy","#1a1a1a","none","smug","smile","🎭")),
 c("Adial","Rolling In The Vocals","modern",["musician"],[45,65,85,45,80,93],
   [["Belting",96,"🎤"],["Upbeat Songs",25,"😢"],["Between-Song Banter",90,"😂"],
    ["Breakup Material",95,"💔"],["Award Sweeps",92,"🏆"],["Tour Frequency",30,"📅"]],
   "gold", av("#2a2a3a","#f0d8c0","wavy","#3a2a1a","none","wink","smile","🎤")),
 c("Nicki Vinaj","Alter Egos Included","internet",["musician","entertainer"],[45,70,82,70,75,92],
   [["Verse Speed",95,"🎤"],["Chill",20,"💅"],["Alter Ego Count",90,"🎭"],
    ["Feature Value",93,"⭐"],["Barb Army",90,"🐝"],["Consistency",40,"🔀"]],
   "gold", av("#c94fc4","#a8703a","wavy","#ff2ec4","none","smug","smirk","🎤")),
]

# ─────────────────────────────────────────────
# BATCH 6 — MYTHICAL CREATURES & MONSTERS (public domain)
# ─────────────────────────────────────────────
BATCH_6 = [
 q("The Satyr","Half Goat, Full Liability","ancient",["cryptid","chaos"],"gold","🐐","monster"),
 q("The Lamia","Nursery's Worst Yelp Review","ancient",["villain","cryptid"],"holo","🐍","monster"),
 q("The Hydra","Every Haircut Makes It Worse","ancient",["cryptid","survivor"],"legendary","🐉","monster"),
 q("The Chimera","Designed By Committee","ancient",["cryptid","chaos"],"gold","🦁","monster"),
 q("Pegasus","Horse With Premium Airfare","ancient",["animal","wholesome"],"gold","🪽","monster"),
 q("The Cyclops","Depth Perception Optional","ancient",["cryptid","warlord"],"gold","👁️","monster"),
 q("The Siren","Worst Cruise Entertainment","ancient",["cryptid","musician"],"gold","🎵","monster"),
 q("The Harpy","One-Star Delivery Bird","ancient",["cryptid","chaos"],"silver","🪶","monster"),
 q("The Centaur","Business Up Front, Horse Out Back","ancient",["cryptid","athlete"],"gold","🏹","monster"),
 q("The Phoenix","Subscription-Based Immortality","ancient",["entity","survivor"],"holo","🔥","monster"),
 q("Scylla And Charybdis","No Good Lane Choice","classical",["cryptid","warlord"],"legendary","🌊","monster"),
 q("Leviathan","Ocean's Final Boss","ancient",["entity","warlord"],"legendary","🌊","monster"),
 q("The Basilisk","Eye Contact Ends The Meeting","classical",["cryptid","villain"],"gold","🐍","monster"),
 q("The Cockatrice","Chicken With Legal Liability","classical",["cryptid","chaos"],"silver","🐔","monster"),
 q("The Griffin","Airport Security's Worst Day","ancient",["cryptid","animal"],"gold","🦅","monster"),
 q("The Hippogriff","Respect The Weird Horse Eagle","classical",["cryptid","wholesome"],"gold","🪽","monster"),
 q("The Roc","Carry-On Limit: One Elephant","classical",["cryptid","warlord"],"gold","🦅","monster"),
 q("The Djinn","Read The Fine Print On Wishes","classical",["entity","hustler"],"holo","🪔","monster"),
 q("The Golem","Clay-Based Security System","classical",["entity","survivor"],"gold","🗿","monster"),
 q("The Kelpie","Absolutely Not A Normal Horse","classical",["cryptid","villain"],"silver","🐴","monster"),
 q("The Selkie","Coat Check Has Consequences","classical",["cryptid","wholesome"],"silver","🦭","monster"),
 q("The Banshee","Volume Warning Not Included","classical",["cryptid","musician"],"gold","😱","monster"),
 q("The Dullahan","Head Of Transportation","classical",["cryptid","villain"],"gold","🎃","monster"),
 q("The Goblin King","Underground Middle Management","classical",["ruler","chaos"],"gold","👺","monster"),
 q("The Ogre","Layers, Allegedly","timeless",["cryptid","survivor"],"silver","🧅","monster"),
 q("The Bridge Troll","Toll Booth With Riddles","timeless",["cryptid","hustler"],"silver","🌉","monster"),
 q("The Werewolf","Calendar-Dependent Anger Issues","classical",["cryptid","animal"],"gold","🐺","monster"),
 q("The Mummy","Unwrap At Your Own Risk","ancient",["entity","survivor"],"gold","🧻","monster"),
 q("The Invisible Man","Present, Technically","industrial",["entity","villain"],"gold","🫥","monster"),
 q("The Boogeyman","Under-Bed Property Manager","timeless",["entity","villain"],"gold","🛏️","monster"),
 q("The Sandman","Aggressive Sleep Consultant","timeless",["entity","wholesome"],"gold","💤","monster"),
 q("Jack Frost","Window Defacement Specialist","timeless",["entity","chaos"],"gold","❄️","monster"),
]

# BATCH 7 — PROFESSIONAL MENACES (universal workplace archetypes)
BATCH_7 = [
 q("The Night Shift Nurse","Running On Caffeine And Alarms","modern",["survivor","wholesome"],"gold","🩺","job"),
 q("The Public Defender","Eighty Cases, One Lunch Break","modern",["genius","survivor"],"gold","⚖️","job"),
 q("The Middle School Principal","Hallway Final Boss","modern",["ruler","survivor"],"silver","📣","job"),
 q("The Wedding DJ","Requests Closed After September","modern",["musician","entertainer"],"silver","🎧","job"),
 q("The Mall Cop","Jurisdiction: Food Court","modern",["warlord","entertainer"],"silver","🛴","job"),
 q("The Barista","Spelling Is A Creative Choice","modern",["hustler","artist"],"silver","☕","job"),
 q("The Line Cook","Dinner Rush War Veteran","modern",["survivor","chaos"],"gold","🍳","job"),
 q("The IT Help Desk","Have You Tried Turning It Off","modern",["genius","survivor"],"gold","🖥️","job"),
 q("The Plumber","Your Emergency Is My Invoice","modern",["inventor","hustler"],"silver","🔧","job"),
 q("The Electrician","Licensed Lightning Wizard","modern",["inventor","survivor"],"gold","⚡","job"),
 q("The Dentist","Asks Questions Mid-Drill","modern",["villain","genius"],"silver","🦷","job"),
 q("The Veterinarian","Patients Bite, Owners Explain","modern",["wholesome","genius"],"gold","🐾","job"),
 q("The Real Estate Agent","Natural Light, Emotional Damage","modern",["hustler","entertainer"],"gold","🏠","job"),
 q("The Insurance Adjuster","Coverage Sold Separately","modern",["villain","hustler"],"silver","📋","job"),
 q("The Tax Auditor","Receipts Or Regrets","modern",["villain","genius"],"gold","🧾","job"),
 q("The Flight Attendant","Smile Secured For Takeoff","modern",["survivor","entertainer"],"gold","✈️","job"),
 q("The Baggage Handler","Your Suitcase Knows What It Did","modern",["athlete","chaos"],"silver","🧳","job"),
 q("The Crossing Guard","Tiny Stop Sign, Absolute Power","modern",["ruler","wholesome"],"silver","🛑","job"),
 q("The Lifeguard","Sunscreen-Fueled Surveillance","modern",["athlete","survivor"],"gold","🛟","job"),
 q("The Camp Counselor","Responsible-ish Adult","modern",["survivor","wholesome"],"silver","🏕️","job"),
 q("The Personal Trainer","One More Means Five","modern",["athlete","villain"],"gold","🏋️","job"),
 q("The Yoga Instructor","Breathe Through The Invoice","modern",["athlete","philosopher"],"silver","🧘","job"),
 q("The Tattoo Artist","Permanent Notes Department","modern",["artist","survivor"],"gold","🖋️","job"),
 q("The Dog Walker","Six Leashes, No Fear","modern",["animal","hustler"],"silver","🦮","job"),
 q("The Food Delivery Rider","Your Fries Took The Scenic Route","internet",["hustler","survivor"],"silver","🛵","job"),
 q("The Rideshare Driver","Five Stars Fund The Silence","internet",["hustler","survivor"],"silver","🚗","job"),
 q("The Street Magician","Your Watch Has Left The Chat","modern",["entertainer","hustler"],"gold","🎩","job"),
 q("The Museum Guard","Paid To Watch You Lean","modern",["survivor","philosopher"],"silver","🖼️","job"),
 q("The Weather Reporter","Standing In The Hurricane For You","modern",["entertainer","survivor"],"gold","🌪️","job"),
 q("The Local News Anchor","Breaking News: Still Smiling","modern",["entertainer","ruler"],"gold","🎙️","job"),
]

# BATCH 8 — OBJECTS, FOOD & DAILY INCONVENIENCES
BATCH_8 = [
 q("The Office Printer","Cyan Low, Morale Lower","modern",["entity","villain"],"gold","🖨️","object"),
 q("The Smoke Detector","Battery Crisis At 3 A.M.","modern",["entity","chaos"],"silver","🚨","object"),
 q("Battery Saver Mode","One Percent And Thriving","internet",["entity","survivor"],"silver","🪫","object"),
 q("The Tangled Earbuds","Pocket-Born Geometry Problem","modern",["entity","chaos"],"silver","🎧","object"),
 q("The Fitted Sheet","Folds Nobody, Fears Nobody","modern",["entity","villain"],"silver","🛏️","object"),
 q("The Missing Sock","Witness Protection Program","timeless",["entity","hustler"],"silver","🧦","object"),
 q("The Leftover Container","Lid Sold In Another Dimension","modern",["entity","survivor"],"silver","🥡","object"),
 q("The Office Microwave","Fish Reheater Of Doom","modern",["entity","villain"],"gold","♨️","object"),
 q("The Team Assignment","One Worker, Four Names","modern",["entity","villain"],"gold","📊","object"),
 q("The Password Reset","Your New Password Was Your Old One","internet",["entity","villain"],"gold","🔐","object"),
 q("Predictive Text","Ducking Up Every Message","internet",["entity","chaos"],"gold","⌨️","object"),
 q("The Spam Folder","Where Important Emails Vacation","internet",["entity","hustler"],"silver","📨","object"),
 q("The Loading Spinner","Patience Benchmark","internet",["entity","villain"],"gold","🔄","object"),
 q("The Broken Escalator","Stairs With A Backstory","modern",["entity","survivor"],"silver","🪜","object"),
 q("The Airport Carpet","Seen Things At Gate B12","modern",["entity","survivor"],"silver","🛫","object"),
 q("The Shopping Cart Wheel","Pulls Hard Left","modern",["entity","chaos"],"silver","🛒","object"),
 q("Flat-Pack Furniture","Three Screws Left Means Success","modern",["entity","inventor"],"gold","🪑","object"),
 q("The Plastic Clamshell","Package Guards The Package","modern",["entity","villain"],"silver","📦","object"),
 q("Glitter","Craft Herpes With Better Branding","modern",["entity","chaos"],"gold","✨","object"),
 q("The Lego Brick","Barefoot Home Defense","modern",["entity","warlord"],"gold","🧱","object"),
 q("The Squeaky Toy","Dog-Operated Alarm System","modern",["entity","animal"],"silver","🦴","object"),
 q("The Banana Peel","Physical Comedy Infrastructure","timeless",["entity","chaos"],"silver","🍌","object"),
 q("Gas Station Sushi","Confidence Test In A Box","modern",["entity","villain"],"gold","🍣","object"),
 q("Decaf Coffee","Hot Bean Betrayal","modern",["entity","villain"],"silver","☕","object"),
 q("The Warm Side Of The Pillow","Sleep's Final Boss","timeless",["entity","villain"],"silver","🥵","object"),
 q("Burnt Popcorn","Office Evacuation Snack","modern",["entity","chaos"],"silver","🍿","object"),
 q("The Stale Fortune Cookie","Yesterday's Prophecy","modern",["entity","philosopher"],"silver","🥠","object"),
 q("The Last Slice","Friendship Stress Test","timeless",["entity","chaos"],"gold","🍕","object"),
 q("Mystery Tupperware","Fridge Archaeology Exhibit","modern",["entity","survivor"],"gold","🧫","object"),
 q("The Ice Cream Machine","Operational Status: Mythical","modern",["entity","villain"],"gold","🍦","object"),
]

# BATCH 9 — ANIMAL CHAOS LEAGUE
BATCH_9 = [
 q("The Honey Badger","Feedback Not Accepted","modern",["animal","survivor"],"gold","🍯","animal"),
 q("The Capybara","Unbothered Department Chair","modern",["animal","wholesome"],"gold","🛁","animal"),
 q("The Axolotl","Regrows Everything But Urgency","modern",["animal","survivor"],"gold","🫧","animal"),
 q("The Quokka","Smiling Through The Chaos","modern",["animal","wholesome"],"gold","📸","animal"),
 q("The Wombat","Cube-Based Logistics","modern",["animal","inventor"],"silver","🧊","animal"),
 q("The Platypus","Nature's Group Project","modern",["animal","chaos"],"gold","🥚","animal"),
 q("The Red Panda","Firefox Without Updates","internet",["animal","wholesome"],"gold","🦊","animal"),
 q("The Sloth","Deadline In Three To Five Days","modern",["animal","survivor"],"silver","🦥","animal"),
 q("The Lemur","Eye Contact At Maximum Volume","modern",["animal","chaos"],"silver","👀","animal"),
 q("The Meerkat","Neighborhood Watch Captain","modern",["animal","ruler"],"silver","🔭","animal"),
 q("The Alpaca","Spits With Plausible Deniability","modern",["animal","chaos"],"silver","🦙","animal"),
 q("The Highland Cow","Haircare Above Visibility","modern",["animal","wholesome"],"gold","🐮","animal"),
 q("The Pygmy Goat","Tiny Hooves, Large Agenda","modern",["animal","chaos"],"silver","🐐","animal"),
 q("The Fainting Goat","Stress Response: Horizontal","modern",["animal","survivor"],"silver","💫","animal"),
 q("The Trash Panda","Dumpster Sommelier","internet",["animal","hustler"],"gold","🗑️","animal"),
 q("The Possum","Playing Dead Is A Strategy","modern",["animal","survivor"],"silver","😵","animal"),
 q("The Skunk","Personal Space Enforcement","modern",["animal","warlord"],"silver","🦨","animal"),
 q("The Porcupine","Hugs Require Waivers","modern",["animal","survivor"],"silver","🦔","animal"),
 q("The Otter","Rock-Based Fine Dining","modern",["animal","wholesome"],"gold","🦦","animal"),
 q("The Beaver","Dam Project Manager","modern",["animal","inventor"],"gold","🪵","animal"),
 q("The Goose","Public Park Warlord","modern",["animal","warlord"],"gold","🪿","animal"),
 q("The Swan","Elegant Until Approached","modern",["animal","villain"],"gold","🦢","animal"),
 q("The Pelican","Throat Storage Solutions","modern",["animal","hustler"],"silver","🐟","animal"),
 q("The Shoebill","Prehistoric HR Stare","modern",["animal","villain"],"gold","🦤","animal"),
 q("The Crow","Shiny Object Intelligence Agency","modern",["animal","genius"],"gold","🐦‍⬛","animal"),
 q("The Pigeon Mayor","Elected By Bread Crumbs","modern",["animal","ruler"],"gold","🗳️","animal"),
 q("The Octopus","Eight-Armed Escape Artist","modern",["animal","genius"],"holo","🐙","animal"),
 q("The Mantis Shrimp","Sees Colors, Chooses Violence","modern",["animal","warlord"],"gold","🦐","animal"),
]

# BATCH 10 — PUBLIC-DOMAIN STORYBOOK ALL-STARS
BATCH_10 = [
 q("Sherlock Holmes","Consulting Detective, Terrible Roommate","industrial",["genius","hustler"],"holo","🔎","storybook"),
 q("Dr. Watson","Narrator With Medical Benefits","industrial",["wholesome","survivor"],"gold","🩺","storybook"),
 q("Professor Moriarty","Tenure-Track Crime Lord","industrial",["genius","villain"],"holo","♟️","storybook"),
 q("Alice Of Wonderland","Curiosity With Plot Armor","industrial",["survivor","chaos"],"gold","🫖","storybook"),
 q("The Mad Hatter","Tea Time Has No Exit","industrial",["chaos","entertainer"],"gold","🎩","storybook"),
 q("The Queen Of Hearts","Performance Reviews By Beheading","industrial",["ruler","villain"],"gold","❤️","storybook"),
 q("The White Rabbit","Late Since 1865","industrial",["animal","survivor"],"silver","⌚","storybook"),
 q("The Cheshire Cat","Smirk First, Context Never","industrial",["animal","chaos"],"gold","😸","storybook"),
 q("Peter Pan","Never Updated The Birth Year","industrial",["survivor","chaos"],"gold","🧚","storybook"),
 q("Captain Hook","Clock-Triggered Management Style","industrial",["villain","warlord"],"gold","🪝","storybook"),
 q("Tinker Bell","Tiny Body, Nuclear Temper","industrial",["entity","chaos"],"gold","✨","storybook"),
 q("Long John Silver","Employee Of The Month: Mutiny","industrial",["hustler","villain"],"gold","🏴‍☠️","storybook"),
 q("Robinson Crusoe","Remote Work Pioneer","industrial",["survivor","inventor"],"gold","🏝️","storybook"),
 q("Dorian Gray","Portrait Handles The Consequences","industrial",["artist","villain"],"gold","🖼️","storybook"),
 q("Dr. Jekyll","Work-Life Balance Researcher","industrial",["genius","inventor"],"gold","🧪","storybook"),
 q("Mr. Hyde","The Side Effect Won","industrial",["villain","chaos"],"gold","💥","storybook"),
 q("Captain Nemo","Submarine Owner, Surface Hater","industrial",["genius","ruler"],"holo","🦑","storybook"),
 q("Phileas Fogg","Around The World On A Spreadsheet","industrial",["hustler","survivor"],"gold","🌍","storybook"),
 q("Don Quixote","Windmill Opposition Leader","renaissance",["warlord","chaos"],"gold","🐴","storybook"),
 q("Sancho Panza","Designated Reality Checker","renaissance",["wholesome","survivor"],"silver","🥘","storybook"),
 q("Cyrano De Bergerac","Ghostwriter With A Sword","renaissance",["artist","warlord"],"gold","🪶","storybook"),
 q("Edmond Dantes","Revenge Project Manager","industrial",["hustler","survivor"],"holo","💎","storybook"),
 q("Quasimodo","Bell Tower Remote Employee","renaissance",["survivor","wholesome"],"gold","🔔","storybook"),
 q("Ichabod Crane","One Pumpkin From Retirement","industrial",["survivor","philosopher"],"silver","🎃","storybook"),
 q("Rip Van Winkle","Twenty-Year Power Nap","industrial",["survivor","chaos"],"silver","💤","storybook"),
 q("Tom Sawyer","Outsourced The Fence","industrial",["hustler","chaos"],"gold","🪣","storybook"),
 q("Huckleberry Finn","Raft-Based Life Coach","industrial",["survivor","wholesome"],"gold","🛶","storybook"),
 q("Ebenezer Scrooge","Three Ghosts, One HR Complaint","industrial",["hustler","villain"],"gold","🪙","storybook"),
 q("Tiny Tim","Carried The Entire Ending","industrial",["wholesome","survivor"],"gold","🩼","storybook"),
 q("Little Red Riding Hood","Basket-Based Threat Detection","timeless",["survivor","wholesome"],"silver","🧺","storybook"),
 q("The Big Bad Wolf","Home Inspector Without A License","timeless",["animal","villain"],"gold","🐺","storybook"),
 q("The Three Little Pigs","Building Code Learning Curve","timeless",["animal","inventor"],"gold","🏠","storybook"),
]

# BATCH 11 — TERMINALLY ONLINE ARCHETYPES
BATCH_11 = [
 q("The Unread Email","Marked Important Since Tuesday","internet",["entity","villain"],"silver","📧","online"),
 q("The Muted Group Chat","Peace Through Neglect","internet",["entity","survivor"],"silver","🔕","online"),
 q("The Password Sharer","Family Plan Revolutionary","internet",["hustler","wholesome"],"silver","🔑","online"),
 q("The Tab Hoarder","Forty-Seven Open, None Relevant","internet",["internet","survivor"],"gold","🗂️","online"),
 q("The Incognito Historian","Research Leaves No Footprints","internet",["internet","hustler"],"gold","🕵️","online"),
 q("The Notification Swiper","Read Nothing, Cleared Everything","internet",["internet","survivor"],"silver","👉","online"),
 q("The Two-X Podcaster","Free Time Through Speed","internet",["internet","genius"],"gold","🎧","online"),
 q("The Voice Note Novelist","Seven Minutes, No Chapters","internet",["entertainer","chaos"],"silver","🎙️","online"),
 q("The Calendar Decliner","Protecting The Block","internet",["ruler","survivor"],"gold","📅","online"),
 q("The LinkedIn Poet","Thrilled To Announce A Paragraph","internet",["internet","hustler"],"gold","💼","online"),
 q("The Fitness App Liar","Forgot To Stop The Workout","internet",["internet","athlete"],"silver","🏃","online"),
 q("The Screenshot Archivist","Receipts Department","internet",["internet","genius"],"gold","📸","online"),
 q("The Typing Bubble","Three Dots Of Emotional Terror","internet",["entity","villain"],"gold","💬","online"),
 q("Left On Read","Silence With A Timestamp","internet",["entity","villain"],"gold","👁️","online"),
 q("The Wi-Fi Moocher","One Bar, Zero Shame","internet",["hustler","survivor"],"silver","📶","online"),
 q("The QR Menu Hater","Bring Back Laminated Civilization","internet",["philosopher","villain"],"silver","📱","online"),
 q("Update Later","Tomorrow's Security Problem","internet",["entity","survivor"],"silver","⬆️","online"),
 q("The Cookie Banner","Reject All Hidden On Page Nine","internet",["entity","villain"],"gold","🍪","online"),
 q("The CAPTCHA Veteran","Has Identified Every Bus","internet",["survivor","genius"],"gold","🚌","online"),
 q("The Two-Factor Wanderer","Code Sent To The Other Phone","internet",["survivor","chaos"],"silver","6️⃣","online"),
 q("The AirDrop Stranger","Nearby And Unsupervised","internet",["internet","chaos"],"gold","📲","online"),
 q("The Reply-All Hero","Company-Wide Main Character","internet",["internet","chaos"],"gold","📣","online"),
 q("The Email Meeting","Could Have Been Nothing","internet",["entity","villain"],"gold","📆","online"),
 q("The Hot Mic","Career Development Device","internet",["entity","chaos"],"gold","🎤","online"),
 q("The Camera-Off Champion","Present In Spirit And Pajamas","internet",["internet","survivor"],"silver","📵","online"),
 q("The Virtual Background","Kitchen Witness Protection","internet",["entity","hustler"],"silver","🏝️","online"),
 q("Screen Share Panic","Desktop Suddenly Public","internet",["entity","chaos"],"gold","🖥️","online"),
 q("The Cloud Storage Warning","Pay Up Or Pick A Memory","internet",["entity","villain"],"gold","☁️","online"),
 q("One Percent Battery","Living Without A Charger","internet",["entity","survivor"],"gold","🪫","online"),
 q("The Broken Link","Destination: Disappointment","internet",["entity","villain"],"silver","🔗","online"),
 q("The Subscription Wall","Journalism's Toll Troll","internet",["entity","hustler"],"gold","🧱","online"),
 q("Terms And Conditions","Nobody Read The Final Boss","internet",["entity","villain"],"holo","📜","online"),
]

BATCHES = [BATCH_1, BATCH_2, BATCH_3, BATCH_4, BATCH_5, BATCH_6, BATCH_7, BATCH_8, BATCH_9, BATCH_10, BATCH_11]

def emit():
    cards = [x for b in BATCHES for x in b]
    # collision guard
    existing = set(json.load(open('scripts/existing_names.json')))
    seen = set()
    for card in cards:
        if card['name'] in existing:
            print("COLLISION with existing:", card['name']); sys.exit(1)
        if card['name'] in seen:
            print("DUPLICATE in roster:", card['name']); sys.exit(1)
        seen.add(card['name'])
    J = json.dumps
    lines = []
    lines.append("// AUTO-GENERATED by scripts/gen_roster.py — DO NOT EDIT BY HAND.")
    lines.append("// Single source of truth for the expansion roster: one object per card,")
    lines.append("// emitted into presetCards + cardRegistry + avatar with zero desync.")
    lines.append("import type { Era, Tag, CardGameData, CoreStats } from '@/data/cardRegistry';")
    lines.append("import type { AvatarTraits } from '@/lib/avatar';")
    lines.append("import type { PresetCard } from '@/data/presetCards';")
    lines.append("")
    lines.append("export interface RosterCard {")
    lines.append("  name: string; nickname: string; era: Era; tags: Tag[];")
    lines.append("  core: CoreStats; stats: { label: string; value: number; emoji: string }[];")
    lines.append("  rarity: PresetCard['rarity']; avatar: AvatarTraits;")
    lines.append("}")
    lines.append("")
    lines.append("function c(name: string, nickname: string, era: Era, tags: Tag[], core: [number,number,number,number,number,number], stats: [string, number, string][], rarity: PresetCard['rarity'], avatar: AvatarTraits): RosterCard {")
    lines.append("  return { name, nickname, era, tags, core: { might: core[0], brains: core[1], charm: core[2], chaos: core[3], grit: core[4], clout: core[5] }, stats: stats.map(([label, value, emoji]) => ({ label, value, emoji })), rarity, avatar };")
    lines.append("}")
    lines.append("")
    lines.append("export const ROSTER: RosterCard[] = [")
    for card in cards:
        core = ",".join(str(int(x)) for x in card['core'])
        stats = ", ".join("[%s, %d, %s]" % (J(s[0]), int(s[1]), J(s[2])) for s in card['stats'])
        a = card['av']
        avs = "{ bg: %s, skin: %s, hair: %s, hairColor: %s, facial: %s, eyes: %s, mouth: %s, prop: %s }" % (
            J(a['bg']), J(a['skin']), J(a['hair']), J(a['hairColor']), J(a['facial']), J(a['eyes']), J(a['mouth']), J(a['prop']))
        tags = "[" + ", ".join(J(t) for t in card['tags']) + "]"
        lines.append("  c(%s, %s, %s, %s, [%s], [%s], %s, %s)," % (
            J(card['name']), J(card['nick']), J(card['era']), tags, core, stats, J(card['rarity']), avs))
    lines.append("];")
    lines.append("")
    lines.append("export const ROSTER_REGISTRY: Record<string, CardGameData> = Object.fromEntries(ROSTER.map(c => [c.name, { era: c.era, tags: c.tags, core: c.core }]));")
    lines.append("export const ROSTER_AVATARS: Record<string, AvatarTraits> = Object.fromEntries(ROSTER.map(c => [c.name, c.avatar]));")
    lines.append("export const ROSTER_PRESET_BASE: Omit<PresetCard, 'image'>[] = ROSTER.map(c => ({ name: c.name, nickname: c.nickname, stats: c.stats, rarity: c.rarity }));")
    lines.append("")
    open('src/data/megaRoster.ts','w').write("\n".join(lines))
    print("emitted", len(cards), "roster cards")

if __name__ == '__main__':
    emit()
